package com.unicorn.rest.repository.table;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.inject.Singleton;

import com.unicorn.rest.repository.exception.DuplicateKeyException;
import com.unicorn.rest.repository.exception.ItemNotFoundException;
import com.unicorn.rest.repository.exception.RepositoryServerException;
import com.unicorn.rest.repository.exception.StaleDataException;
import com.unicorn.rest.repository.exception.ValidationException;
import com.unicorn.rest.repository.model.EmailAddress;

/**
 * TODO: JavaMail (http://www.oracle.com/technetwork/java/javamail/index.html)
 * sending email to verify the email address
 */
@Singleton
public interface EmailAddressToUserIdTable extends Table {

    /**
     * Create email_address to user_id mapping in the email_address_to_id_table
     * The activate_in_epoch time is generated by server
     * 
     * @param emailAddress @Nullable
     * @param userId @Nullable
     * @throws ValidationException if request is invalid
     * @throws DuplicateKeyException if email_address is already mapped to existing user_id
     * @throws RepositoryServerException internal server error
     */
    public void createEmailAddressForUserId(@Nullable EmailAddress emailAddress, @Nullable Long userId) 
            throws ValidationException, DuplicateKeyException, RepositoryServerException;
    
    /**
     * Get the current email_address to user_id from email_address_to_id_table
     * create new email_address to user_id mapping in the email_address_to_id_table
     * and delete the old email_address to user_id mapping
     * 
     * Note:
     * This might encounter some problems when there exists concurrent update requests for the same user
     * However, we consider this as a rare case
     * 
     * If the create operation succeeds yet the delete operation failed, there is a 
     * chance that user will have multiple email_addresses to log in. 
     * However, we can still figure out which one is the latest by checking the activate_in_epoch 
     * 
     * @param curEmailAddress @Nullable
     * @param newEmailAddress @Nullable
     * @param userId @Nullable
     * @throws ValidationException if request is invalid
     * @throws DuplicateKeyException if new email_address is already mapped to existing user_id   
     * @throws ItemNotFoundException if email_address attempted to deleted mapped to a different user_id or user_id does not exist
     * @throws RepositoryServerException internal server error
     */
    public void updateEmailAddressForUserId(@Nullable EmailAddress curEmailAddress, @Nullable EmailAddress newEmailAddress, @Nullable Long userId) 
            throws ValidationException, DuplicateKeyException, ItemNotFoundException, RepositoryServerException;
    
    /**
     * Get user_id for given email_address
     * 
     * @param emailAddress @Nullable
     * @return
     * @throws ValidationException if request is invalid
     * @throws ItemNotFoundException if email_address does not exist in the table
     * @throws RepositoryServerException internal server error
     */
    public @Nonnull Long getUserId(@Nullable EmailAddress emailAddress) 
            throws ValidationException, ItemNotFoundException, RepositoryServerException;
    
    /**
     * Get email_address for user_id.
     * 
     * Note:
     * Since user_id-actiavet_in_epoch is global secondary index, there is currently no strong consistency.
     * meaning that there is a certain chance we will get stale data. 
     * However, we can check if the data is actually state by looking up the email address again.
     * What is more, since failure can happen when user updates email_address (successfully created the new one, yet failed to delete old one),
     * user might have multiple email_addresses, but we can easily figure out the latest one 
     * by check the activate_in_epoch
     * 
     * @param userId @Nullable
     * @return
     * @throws ValidationException if request is invalid
     * @throws ItemNotFoundException if the user_id does not exist in the table
     * @throws StaleDataException if the server detected stale data for this request (only when checkStaleness flag is set true)
     * @throws RepositoryServerException internal server error
     */
    public @Nonnull String getEmailAddress(@Nullable Long userId, boolean checkStaleness) 
            throws ValidationException, ItemNotFoundException, StaleDataException, RepositoryServerException;
    
    
}
